core:
  trash:
    strategy: auto
    home_fallback: true
  restore:
    confirm: false
    verbose: true
  permanent_delete:
    enable: false

ui:
  density: spacious
  preview:
    syntax_highlight: true
    colorscheme: nord
  style:
    list_view:
      cursor: "#AD58B4"
      selected: "#5FB458"
      filter_match: "#F39C12"
      filter_prompt: "#7AA2F7"
      indent_on_select: false
    detail_view:
      border: "#FFFFFF"
    deletion_dialog: "#FF007F"
  exit_message: bye!
  paginator_type: dots

history:
  include:
    within_days: 100
  exclude:
    files:
      - .DS_Store

logging:
  enabled: false
  level: info
  rotation:
    max_size: 10MB
    max_files: 3
