# vim:set ft=tmux:
# Custom Catppuccin "flags" status module. Shows non-default modal state:
# sync panes, mouse off, and zoom.

%hidden MODULE_NAME="flags"

set -ogq  "@catppuccin_${MODULE_NAME}_icon"  " "
set -ogqF "@catppuccin_${MODULE_NAME}_color" "#{?pane_synchronized,#{E:@thm_red},#{?mouse,#{E:@thm_yellow},#{E:@thm_red}}}"
set -ogq  "@catppuccin_${MODULE_NAME}_text"  " #{?pane_synchronized,SYNC ,}#{?mouse,,MOUSE-OFF }#{?window_zoomed_flag,ZOOM ,}"

source -F "#{d:current_file}/plugins/tmux/utils/status_module.conf"
