# vim:set ft=tmux:
# Custom Catppuccin "ram" status module. Uses tmux-cpu's #{ram_percentage}.
# Kept in config dir (not in plugin) so TPM updates don't clobber.

%hidden MODULE_NAME="ram"

set -ogq  "@catppuccin_${MODULE_NAME}_icon"  " "
set -ogqF "@catppuccin_${MODULE_NAME}_color" "#{E:@thm_mauve}"
set -ogq  "@catppuccin_${MODULE_NAME}_text"  " #($HOME/.config/tmux/bin/ram-percentage.sh)"

source -F "#{d:current_file}/plugins/tmux/utils/status_module.conf"
