
[appearance]
mode = "automatic"

[borders]
enabled = true
width = 2.5

[borders.color]
alpha = 1.0
blue = 0.02599336511233563
green = 0.03175824726289883
red = 1.0

[focus]
followsMouse = false
followsWindowToMonitor = true
moveMouseToFocusedWindow = false

[gaps]
size = 5.0

[gaps.outer]
bottom = 0.0
left = 0.0
right = 0.0
top = 0.0

[general]
developerModeEnabled = false
hotkeysEnabled = true
ipcEnabled = false
preventSleepEnabled = false

[gestures]
fingerCount = 4
invertDirection = true
mouseResizeModifierKey = "option"
scrollEnabled = true
scrollModifierKey = "optionShift"
scrollSensitivity = 5.0

[mouseWarp]
axis = "horizontal"
margin = 1
monitorOrder = []

[niri]
balancedColumnCount = 2
columnWidthPresets = [0.35, 0.5, 0.65, 0.95]
infiniteLoop = true
revealPartial = "default"

[statusBar]
showAppNames = false
showWorkspaceName = false
useWorkspaceId = false

[workspaceBar]
backgroundOpacity = 0.1
deduplicateAppIcons = true
enabled = false
height = 24.0
hideEmptyWorkspaces = true
labelFontSize = 12.0
notchAware = false
position = "overlappingMenuBar"
reserveLayoutSpace = false
showFloatingWindows = true
showLabels = false
showTraceButton = false
windowLevel = "popup"
xOffset = 0.0
yOffset = 0.0
