# cmux-resurrect layout: autosave
# Saved at: 2026-04-14T18:47:57Z

name = 'autosave'
description = 'autosave'
version = 1
saved_at = 2026-04-14T18:47:57.251972Z

[[workspace]]
title = 'Learn'
cwd = '/Users/yushi/note'
pinned = true
index = 0

[[workspace.pane]]
type = 'terminal'
focus = true

[[workspace]]
title = '~/project/echo'
cwd = '/Users/yushi/project/echo'
pinned = false
index = 1
active = true

[[workspace.pane]]
type = 'terminal'
focus = true
